spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK-URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: ${REALM}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  grant-type: ${GRANT_TYPE}

server:
  port: 8443
  # ssl:
  #   key-store-type: PKCS12
  #   key-store: classpath:keystore.p12
  #   key-store-password: certpass123
